### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by grael2** [khashishin/Vis-AW#3]
- wyświetlanie na wizualizacji oryginalnych nazw obiektów - DONE
- przerobienie na exe DONE
- dokończenie samego algorytmu - DONE

**Comment by ghost** [comment]
- sprawdzić jaka jest różnica między miernikiem z wagami a bez wag (mały detal ale istotny)
- refaktorke na sam szary koniec

**Comment by grael2** [comment]
- znaleźć ikonę - DONE - http://www.flaticon.com/free-icon/share_14539#term=network&page=1&position=25
- dodać metody liczenia odległości
- zwracać wartość krytyczną https://pl.wikipedia.org/wiki/Dendryt_wroc%C5%82awski DONE
- poprawić README.md DONE

**Comment by khashishin** [comment]
<li> Dodać do raportu wyniki ze statistici z opisem i tokiem naszych badań (i napisać co było nie do zrobienia, ciężkie do intepretacji i co zmienia się jak wykorzystujemy tyle danych w stosunku do tego co na zajęciach) DONE
<li> Dodać opis implementacji do Raportu DONE
<li> Zaimplementować inne sposoby liczenia odległości w programie 
<li> Dodać do raportu opis pliku excela który jest wymagany do działania programu DONE
<li> Dodać przykładową wizualizację i macierz odległości w screenach do raportu, za ich pomocą też zdebuggować czy program się nie myli

**Comment by grael2** [comment]
- Usunąć foldery "wizualizacje" i dodać w kodzie tworzenie go, jeżeli go nie ma w lokalizacji uruchomieniowej
